#!/bin/bash
#
#   Script Backup Mikrotik
#
#   Features:
#   - Create backup user into Routerboard
#   - Connect with ssh key
#   - Make dump Backup and Export file
#   - Verify version Firmware and model
#   - Run update commands.
#   - Copy to server backup file
#   - Send email report.
#
#   Contributors
#   - ST Duwe CBMSC
#   - Sgt Leonardo CBMSC
#   - Sd Jorge CBMSC
#
##################################################
#    Config File Environments
##################################################
export folder=/root/scripts/bkmk            #Directory where backup scripts are located.
export servers=$folder/bkmk.cid             #File where you will get the servers to perform the backup.
export script=$folder/bkmk.sh               #File that performs the backup.
export folder_destiny=/var/bkp/mikrotik     #Backup folder.
export update=$folder/bkmk.update           #File with commands to update.
export sshuser=bkmk                         #User to ssh the backup.
export userdefault=userAdminRouter          #Power user to create user bkmk ssh the backup.
export password_default=PasswdAdminRouter   #Power pass to create user bkmk ssh the backup.
export log=$folder/log/$data.log            # Backup log file name and location.
export days=5                               # Number of days to keep log files.
export daysbkp=365                          # Number of days to keep log files.
export commands_update=bkmk.update          # Commands that will be executed in the update.
#Email where you will send the backup report.
export email="ORGANIZATION <myemail@mydomain.etc>;<otheremail@mydomain.etc>"	

export data=`date +%F-%A-%H-%M`
export data_file=`date +%d-%m-%y`
export hour=`date +%H:%M`

#Running the backup script
nice -n +19 bash $script 2>&1 | tee $log

# Sending backup log email:
IFS=:
sendmail $email << EOF
Subject: [BACKUP] Firewalls - `date +%F`. Total erros: `cat /tmp/errors`/`cat /tmp/up`
From: Server Backup <`hostname`@mydomain.etc>
To: $email

Total errors: `cat /tmp/errors`

Routers with errors:
`cat /tmp/servers`/`cat /tmp/up`

List version routers
`cat /tmp/upgrade`

Report Backup:
`cat $log`


--------------------
Att.
Backup Team `hostname`
EOF
